version: ~> 1.0
dist: bionic
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install: pip install .[test] codecov
script: ./run-tests.py
before_cache: rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
